server:
  port: 8001

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: concert-service
          uri:  http://localhost:8082
          predicates:
            - Path=/concert-service/**
          filters:
            - RewritePath=/concert-service/(?<segment>.*), /$\{segment}

jwt:
  secret: yourSecretKeyHereMustBeAtLeast32BytesLong
  expire-length: 36000000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true