spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  kafka:
    bootstrap-servers: localhost:9092